version: '3.8'

services:
  # Ollama service for AI models
  ollama:
    image: ollama/ollama:latest
    container_name: meetingscribe-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MeetingScribe AI application
  app:
    build: .
    container_name: meetingscribe-app
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - OLLAMA_API_URL=http://ollama:11434/api/generate
      - WHISPER_MODEL=whisper
      - OLLAMA_MODEL=llama3.2:3b
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  ollama_data:
    driver: local